### PR TITLE
Update color.tsx

### PR DESCRIPTION
**Pull request by CrazyLames22**

### CODE REVIEW

**Comment by marinofranz** [comment]
> Can you leave a description of what you added/removed?

They were adding a separate theme color available.

**Comment by marinofranz** [comment]
You should also close this PR and open one to combine all 3 you made.

**Comment by CrazyLames22** [comment]
What?

**Comment by marinofranz** [comment]
> What?

You had multiple PRs open for the same change. Close this PR and open another one for all changes you made.

**Pull request closed without merging**
